version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cognify-postgres
    restart: always
    environment:
      POSTGRES_USER: cognify
      POSTGRES_PASSWORD: cognify123
      POSTGRES_DB: cognifydb
    ports:
      - "5433:5432"
    volumes:
      - cognify_data:/var/lib/postgresql/data
    networks:
      - cognify-network

networks:
  cognify-network:
    driver: bridge

volumes:
  cognify_data:
